define({
    root: {
        select: "Select",
        draw: "Draw",
        chooseALayer: "Select a layer",
        clickAFeature: "Click on a feature on the map to select it.",
        loadingFeatures: "Getting selected feature details...",
        errorTitle: "Error",
        errorIdentify: "Identify features error. Please check console log for details.",
        infoWindowTitle: "Details",
        layerLabel: 'Layer Name',
        reviewStatusLabel: 'Review Status',
        selectReviewStatusAdd: 'Add Feature',
        selectReviewStatusDelete: 'Delete Feature',
        selectReviewStatusMove: 'Move Feature',
        selectReviewStatusReshape: 'Reshape Feature',
        drawReviewStatusMissing: 'Missing Feature(s)',
        drawReviewStatusPosition: 'Positional Error',
        drawReviewStatusShape: 'Shape Error',
        drawReviewStatusAttribute: 'Attribute Error',
        notesLabel: 'Notes',
        severityLabel: 'Severity',
        reportedByLabel: 'Reported By',
        reportedByDefault: 'anonymous',
        reportButton: 'Report',
        reportMessage: 'Report received',
        errorReportMessage: 'There was an error reporting your feature',
        drawErrorInstructions: 'Select point, line or polygon and draw the error geometry on the map:',
        errorMapService: 'There was an error getting map service information',
        noFeatureSelected : 'There were no features found at the clicked location',
        selectFeatureMapPoint: 'Click to select a feature',
        drawFeatureMapPoint: 'Click to add a point',
        popupMessage:'Message',
        popupError:'Error',
        manyFeaturesSelected: 'More than one feature found. Please zoom in and select a feature to report.'
    }
});
